---
name: "idx"
fs:
  url: "/tmp/es"
  update_rate: "1m"
  indexed_chars: 100%
  lang_detect: true
  continue_on_error: true
  remove_deleted: true
  add_filesize: true
  ocr:
    language: "por"
    enabled: true
    pdf_strategy: "auto"
  includes:
    - "**/*"
  excludes:
    - "*/~*"
    - "**/README.txt"
    - "**/readme.txt"
    - "**/README.md"
    - "**/readme.md"
elasticsearch:
  nodes:
    - url: "https://elasticsearch:9200"
  username: "elastic"
  password: "changeme"
  ssl_verification: false
  index: "documents"
  type: "_doc"
  pipeline: "documents_pipeline"
  bulk_size: 100
  flush_interval: "5s"
  max_bulk_requests: 8
rest:
  url: "http://fscrawler:8080"

